### ISSUE TITLE
Add link to website

### ISSUE THREAD

**Issue by jrasm91** [brasm94/webpage#1]
Repository should have a link to the firebase hosted website at the top and in the **README.md** file:

![image](https://user-images.githubusercontent.com/4334196/33440861-5c2e5a12-d5ae-11e7-97c7-44d8cac26a41.png)

**Comment by kr4of6** [comment]
I added the URL to the REAM.md file. I'm not sure if there is a better way to do that?

**Comment by jrasm91** [comment]
Links have been added.
